// <auto-generated />
using System;
using GripOnMash.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GripOnMash.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241018154904_SeedMediciDiBase")]
    partial class SeedMediciDiBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GripOnMash.Models.Agenda", b =>
                {
                    b.Property<int>("AgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgendaId"));

                    b.Property<string>("GiornoSettimana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("InternalUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroMassimoPazienti")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("OraInizio")
                        .HasColumnType("time");

                    b.Property<DateTime>("ValidoDalGiorno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidoFinoAlGiorno")
                        .HasColumnType("datetime2");

                    b.HasKey("AgendaId");

                    b.HasIndex("InternalUserId");

                    b.ToTable("Agenda", (string)null);
                });

            modelBuilder.Entity("GripOnMash.Models.Appuntamento", b =>
                {
                    b.Property<int>("AppuntamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppuntamentoId"));

                    b.Property<int>("CodiceGenerato")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAppuntamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AppuntamentoId");

                    b.HasIndex("IdentityId");

                    b.ToTable("Appuntamento", (string)null);
                });

            modelBuilder.Entity("GripOnMash.Models.Domanda", b =>
                {
                    b.Property<int>("DomandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DomandaId"));

                    b.Property<string>("DomandaTesto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("DomandaId");

                    b.ToTable("Domanda", (string)null);
                });

            modelBuilder.Entity("GripOnMash.Models.IdentityModel.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a9999779-ae40-4692-9aa5-38a891953a2d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d75fe8d3-8dee-4451-b9a4-8c0c9ea3e5ff",
                            Email = "medicobase1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "MEDICOBASE1@GMAIL.COM",
                            NormalizedUserName = "MEDICOBASE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEEM7p/jwg6PZ87SOvLla7Df8HX0qinMQRa7t/C/wh9yzMi0gn7oEAD3rGUz93PqZ8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "19d6edb3-3dc4-49c5-9b50-97d722613773",
                            TwoFactorEnabled = false,
                            UserName = "medicoBase1"
                        },
                        new
                        {
                            Id = "bce2fa92-4ec6-4bc1-87f1-ba64f25fc5b8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c692da41-4006-4658-a6ea-68c2785e0db0",
                            Email = "medicobase2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "MEDICOBASE2@GMAIL.COM",
                            NormalizedUserName = "MEDICOBASE2",
                            PasswordHash = "AQAAAAIAAYagAAAAEPiIOb+1yGu02GKuzXT6IYsA25Q1kjhKTW/NjLSLiVViyx34qBrX7DnhwM2hdF0Utw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "506e62c1-d882-472c-b4e9-4237df77aa6a",
                            TwoFactorEnabled = false,
                            UserName = "medicoBase2"
                        });
                });

            modelBuilder.Entity("GripOnMash.Models.InternalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("InternalUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8999386-ac1b-47f7-9a90-2bdd4bb88ca9"),
                            Cognome = "Silveri",
                            IsEnabled = true,
                            Matricola = "sb004193",
                            Nome = "Marco"
                        },
                        new
                        {
                            Id = new Guid("f691dc5c-31e0-4e4d-8061-2d2952e4faca"),
                            Cognome = "Picchi",
                            IsEnabled = true,
                            Matricola = "00665539",
                            Nome = "Daniele"
                        },
                        new
                        {
                            Id = new Guid("8b89d683-a564-4f2e-a7b3-aadc5c008d32"),
                            Cognome = "Rossi",
                            IsEnabled = true,
                            Matricola = "sb004194",
                            Nome = "Mario"
                        });
                });

            modelBuilder.Entity("GripOnMash.Models.InternalUserAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Accesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ScadenzaToken")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Uscita")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("InternalUserAccess", (string)null);
                });

            modelBuilder.Entity("GripOnMash.Models.InternalUserRole", b =>
                {
                    b.Property<Guid>("InternalUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InternalUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("InternalUserRole", (string)null);

                    b.HasData(
                        new
                        {
                            InternalUserId = new Guid("b8999386-ac1b-47f7-9a90-2bdd4bb88ca9"),
                            RoleId = "fe232d35-f62d-407f-995b-1934d38d96cc"
                        },
                        new
                        {
                            InternalUserId = new Guid("f691dc5c-31e0-4e4d-8061-2d2952e4faca"),
                            RoleId = "fe232d35-f62d-407f-995b-1934d38d96cc"
                        },
                        new
                        {
                            InternalUserId = new Guid("8b89d683-a564-4f2e-a7b3-aadc5c008d32"),
                            RoleId = "fe232d35-f62d-407f-995b-1934d38d96cc"
                        });
                });

            modelBuilder.Entity("GripOnMash.Models.MedicoBaseAnagrafica", b =>
                {
                    b.Property<int>("MedicoBaseAnagraficaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicoBaseAnagraficaId"));

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailPersonale")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Eta")
                        .HasColumnType("int");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroAlbo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroTelefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PartitaIVA")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Specializzazione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MedicoBaseAnagraficaId");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("MedicoBaseAnagrafica", (string)null);

                    b.HasData(
                        new
                        {
                            MedicoBaseAnagraficaId = 1,
                            CodiceFiscale = "VRDGPP75E20H501Y",
                            Cognome = "Verdi",
                            EmailPersonale = "giuseppe.verdi@gmail.com",
                            Eta = 45,
                            IdentityId = "a9999779-ae40-4692-9aa5-38a891953a2d",
                            Indirizzo = "Via Roma 1, Milano",
                            Nome = "Giuseppe",
                            NumeroAlbo = "12345MI",
                            NumeroTelefono = "123456789",
                            PartitaIVA = "12345678901",
                            Specializzazione = "Cardiologia"
                        },
                        new
                        {
                            MedicoBaseAnagraficaId = 2,
                            CodiceFiscale = "BNCFNC82C15H501Z",
                            Cognome = "Bianchi",
                            EmailPersonale = "francesca.bianchi@gmail.com",
                            Eta = 38,
                            IdentityId = "bce2fa92-4ec6-4bc1-87f1-ba64f25fc5b8",
                            Indirizzo = "Via Torino 10, Torino",
                            Nome = "Francesca",
                            NumeroAlbo = "67890TO",
                            NumeroTelefono = "987654321",
                            PartitaIVA = "98765432109",
                            Specializzazione = "Dermatologia"
                        });
                });

            modelBuilder.Entity("GripOnMash.Models.NumeroPrenotazione", b =>
                {
                    b.Property<int>("NumeroPrenotazioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroPrenotazioneId"));

                    b.Property<bool>("IsFull")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRange")
                        .HasColumnType("int");

                    b.Property<int>("MinRange")
                        .HasColumnType("int");

                    b.HasKey("NumeroPrenotazioneId");

                    b.ToTable("NumeroPrenotazione", (string)null);
                });

            modelBuilder.Entity("GripOnMash.Models.Risposta", b =>
                {
                    b.Property<int>("RispostaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RispostaId"));

                    b.Property<int>("DomandaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorretta")
                        .HasColumnType("bit");

                    b.Property<string>("RispostaTesto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("RispostaId");

                    b.HasIndex("DomandaId");

                    b.ToTable("Risposta", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fe232d35-f62d-407f-995b-1934d38d96cc",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "447b3ca6-bd0b-4e83-baf9-2de7069c10c5",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a9999779-ae40-4692-9aa5-38a891953a2d",
                            RoleId = "447b3ca6-bd0b-4e83-baf9-2de7069c10c5"
                        },
                        new
                        {
                            UserId = "bce2fa92-4ec6-4bc1-87f1-ba64f25fc5b8",
                            RoleId = "447b3ca6-bd0b-4e83-baf9-2de7069c10c5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GripOnMash.Models.Agenda", b =>
                {
                    b.HasOne("GripOnMash.Models.InternalUser", "InternalUser")
                        .WithMany("Agende")
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternalUser");
                });

            modelBuilder.Entity("GripOnMash.Models.Appuntamento", b =>
                {
                    b.HasOne("GripOnMash.Models.IdentityModel.ApplicationUser", "IdentityUser")
                        .WithMany("Appuntamenti")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("GripOnMash.Models.InternalUserRole", b =>
                {
                    b.HasOne("GripOnMash.Models.InternalUser", "InternalUser")
                        .WithMany("InternalUserRoles")
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternalUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GripOnMash.Models.MedicoBaseAnagrafica", b =>
                {
                    b.HasOne("GripOnMash.Models.IdentityModel.ApplicationUser", "IdentityUser")
                        .WithOne("MedicoBaseAnagrafica")
                        .HasForeignKey("GripOnMash.Models.MedicoBaseAnagrafica", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("GripOnMash.Models.Risposta", b =>
                {
                    b.HasOne("GripOnMash.Models.Domanda", "Domanda")
                        .WithMany("Risposte")
                        .HasForeignKey("DomandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domanda");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GripOnMash.Models.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GripOnMash.Models.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GripOnMash.Models.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GripOnMash.Models.IdentityModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GripOnMash.Models.Domanda", b =>
                {
                    b.Navigation("Risposte");
                });

            modelBuilder.Entity("GripOnMash.Models.IdentityModel.ApplicationUser", b =>
                {
                    b.Navigation("Appuntamenti");

                    b.Navigation("MedicoBaseAnagrafica")
                        .IsRequired();
                });

            modelBuilder.Entity("GripOnMash.Models.InternalUser", b =>
                {
                    b.Navigation("Agende");

                    b.Navigation("InternalUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
